CREATE TABLE IF NOT EXISTS runs (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	seconds INT NOT NULL
);
CREATE TABLE IF NOT EXISTS result (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
	run_id INT NOT NULL,
	val INT NOT NULL DEFAULT 0,
	successful INT NOT NULL DEFAULT 0,
	status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
	hash VARCHAR(20) NOT NULL
);